### ISSUE TITLE
Converting base64 to a blank pdf

### ISSUE THREAD

**Issue by Gerlison** [eranbo/react-native-base64#2]
I have a pdf in base64. When I convert it in a web service, it works. But when I use the react-native-base64 it generates a blank pdf. The number of pages comes right, but all of them are blank.

**Comment by eranbo** [comment]
Maybe because it's not supporting some unicode characters.
I'll try to reproduce it and hopefully get a fix for it
Thanks for letting me know

**Comment by Gerlison** [comment]
Any update about it, I'll let you know.
