### ISSUE TITLE
Convert binary to base64

### ISSUE THREAD

**Issue by FauricioValencia** [eranbo/react-native-base64#5]
I have a binary, but when I convert to base64 with library return a wrong base64

**Comment by eranbo** [comment]
Hi @FauricioValencia ,
The library is currently supporting only text input and not binary.
Keep tracking for changes, I'll update when binary will be supported
Thanks,
Eran

**Comment by katasanirohith** [comment]
#6 solves this issue

**Comment by eranbo** [comment]
@FauricioValencia 
Binary support is now available in the latest version.
Thank you for you feedback
