### ISSUE TITLE
Accentuation

### ISSUE THREAD

**Issue by nicolak** [eranbo/react-native-base64#7]
Hello! The library does not correctly convert accented characters. See this JSON:

`W3sib2NvcnJlbmNpYSI6IlRST0NBINNMRU8gIiwiZXF1aXBfZGVzY3JpY2FvIjoiRVRJT1MgMS41L1FCRjc2MjciLCJpZF9lcXVpcCI6MX1d`

In the tag 'ocorrencia' is result: "TROCA LEO"

The correct thing would be: "TROCA ÓLEO"

Can you help me?

**Comment by IgorSasaki** [comment]
What solution did you implement?
