### ISSUE TITLE
Remove the Alert pop-up when the encoding is wrong

### ISSUE THREAD

**Issue by serge-fabiano** [eranbo/react-native-base64#8]
Got an alert pop-up if I try to decode a string which is not base64.
Could you remove it?

**Comment by eranbo** [comment]
Hi @LucasBrazi06 Thanks for posting this issue. I'll take a look at it.
Look for updates - it might take me some time though

**Comment by eranbo** [comment]
Hi @LucasBrazi06
Thank you for the feedback - the alert is now removed and you can use try / catch as the code is now throwing error is this case.
Cheers
